core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
     path('',views.index, name="index"),
          
     path("products/",views.product_list_view, name = "product-list"),
     
     path("category/",views.category_list_view, name = "category-list"),
     
     path("category/<cid>/",views.category_product_list_view, name = "category-product-list"),
     
     path("product/<pid>/",views.product_detail_view, name = "product-detail"),
     
     path("ajax-add-review/<pid>/", views.ajax_add_review, name = "ajax-add-review" ),
     
     path("search/", views.search_view, name="search"),
     
     path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
     
     path("cart/", views.cart_view, name="cart"),
     
     path("delete-from-cart/",views.delete_item_from_cart, name="delete-from-cart"),
     
     path("update-cart/",views.update_cart,name="update-cart"),
     
     path("about_us/", views.about_us, name="about_us"),
     
     path("purchasing_guide/", views.purchasing_guide, name="purchasing_guide"),
     
     path("terms_of_service/", views.TOS, name="terms_of_service"),
     
     path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
     
     path("dashboard/", views.customer_dashboard, name="dashboard"),
     
     path("dashboard/order/<int:id>", views.order_detail, name="order-detail"),
     
     path("wishlist/", views.wishlist_view, name="wishlist"),
     
     path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),
     
     path("remove-from-wishlist/", views.remove_from_wishlist, name="remove-from-wishlist"),

     path("contact/", views.contact, name="contact"),
     
     path("ajax-contact-form/", views.ajax_contact_form, name="ajax-contact-form"),
     # This url is only used for work in progress apps
     path('wip/',views.wip_view, name = "wip" )
]

renisu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls") ),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] 

if (settings.DEBUG):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Write review"}))
    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from taggit.models import Tag
from core.models import Product, Category, CartOrder, CartOrderProducts, ProductImages, wishlist_model, Address, ProductReview
from core.forms import ProductReviewForm
from django.db.models import Count, Avg
# Create your views here.
from django.urls import reverse
from django.conf import settings
from django.contrib import messages
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.core import serializers
from userauths.models import ContactUs

def index(request):
    products = Product.objects.all()
    #products = Product.objects.filter(condition1,condition2,...) <-- this here is to filter products for a specific type of product to be shown
    context = {
        "products":products
    }
    return render(request, 'core/index.html', context)

def category_list_view(request):
    categories = Category.objects.all()
    context = {
        "categories":categories
    }
    return render(request, 'core/category-list.html', context)

def product_list_view(request):
    products = Product.objects.all().order_by("-id")
    tags = Tag.objects.all().order_by("-id")[:6]
    category = Category.objects.all()

    context = {
        "products":products,
        "tags":tags,
        "category":category
    }

    return render(request, 'core/product-list.html', context)

def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(category = category)
    context = {
        "category":category,
        "products":products
    }
    return render(request,"core/category-product-list.html",context)

def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    p_images = product.p_images.all()
    #products = Product.objects.filter(category=product.category).exclude(pid)
    reviews = ProductReview.objects.filter(product=product)
    review_form = ProductReviewForm()
    make_review = True
    
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()
        if user_review_count > 0:
            make_review = False
        
    context = {
        "product":product,
        "p_images":p_images,
        #"products":products,
        "reviews":reviews,
        "review_form":review_form,
        "make_review":make_review
    }
    #print(reviews.review)
    return render(request,'core/product-detail.html',context)

def wip_view(request):
    return render(request, "core/wip.html")

#def product_review_view(request, pid):
#    product = Product.objects.get(pid = pid)
#    reviews = ProductReview.objects.filter(product = product)
#    context = {
#        "product" : product,
#        "reviews" : reviews
#    }
#    return render(request, '')

def ajax_add_review(request, pid):
    product = Product.objects.get(pid=pid)
    user = request.user
    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )
    context = {
        'user':user.username,
        'review':request.POST['review'],
        'rating':request.POST['rating']
    }
    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))
    return JsonResponse(
        {
            'bool': True,
            'context': context,
            'average_reviews': average_reviews,
        }
    )

def search_view(request):
    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        "products": products,
        "query": query,
    }
    return render(request, "core/search.html", context)

def add_to_cart(request):
    cartProduct = {}
    cartProduct[str(request.GET['id'])] = {
        'title':request.GET['title'],
        'qty':request.GET['qty'],
        'price':request.GET['price'],
        'img':request.GET['img'],
        'pid':request.GET['pid'],
    }
    
    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cartProduct[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cartProduct)
            request.session['cart_data_obj'] = cart_data 
    else:
        request.session['cart_data_obj'] = cartProduct
    return JsonResponse({"data":request.session['cart_data_obj'], 'totalCartItems':len(request.session['cart_data_obj'])})

def cart_view(request):
    cart_total_amt = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amt += int(item['qty']) * float(item['price'])
        return render(request,"core/cart.html", {"cart_data":request.session['cart_data_obj'], 'totalCartItems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amt})
    else:
        #return render(request,"core/cart.html",{"cart_data":'', 'totalCartItems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amt})
        messages.warning(request,"your cart is empty")
        return redirect("core:index")

def delete_item_from_cart(request):
    cart_total_amt = 0
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data

    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amt += int(item['qty']) * float(item['price'])
    
    context = render_to_string("core/async/cart-list.html", {"cart_data":request.session['cart_data_obj'], 'totalCartItems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amt})
    return JsonResponse({"data":context, "totalCartItems":len(request.session['cart_data_obj'])})

def update_cart(request):
    cart_total_amt = 0
    product_id = str(request.GET['id'])
    product_qty = request.GET['qty']
    
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = product_qty
            request.session['cart_data_obj'] = cart_data

    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amt += int(item['qty']) * float(item['price'])
    
    context = render_to_string("core/async/cart-list.html", {"cart_data":request.session['cart_data_obj'], 'totalCartItems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amt})
    return JsonResponse({"data":context, "totalCartItems":len(request.session['cart_data_obj'])})


def about_us(request):
    products = Product.objects.all()
    context = {
        "products":products
    }
    return render(request, "core/about_us.html", context)

def purchasing_guide(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    context = {
        "products":products,
        "categories":categories
    }
    return render(request, "core/purchasing_guide.html", context)

def TOS(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    context = {
        "products":products,
        "categories":categories
    }
    return render(request,"core/terms_of_service.html", context)

def privacy_policy(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    context = {
        "products":products,
        "categories":categories
    }
    return render(request,"core/privacy_policy.html", context)

@login_required
def customer_dashboard(request):
    orders = CartOrder.objects.filter(user=request.user).order_by("-id")
    address = Address.objects.filter(user=request.user)
    
    if request.method == "POST":
        address = request.POST.get("address")
        mobile = request.POST.get("mobile")

        new_address = Address.objects.create(
            user=request.user,
            address=address,
            mobile=mobile,
        )
        messages.success(request, "Address Added Successfully.")
        return redirect("core:dashboard")
    else:
        print("Error")
        
    context = {
        "orders":orders,
        "address":address
    }
    return render(request,"core/dashboard.html", context)

def order_detail(request, id):
    order = CartOrder.objects.get(user=request.user, id =id)
    products = CartOrderProducts.objects.filter(order=order)
    context = {
        "products": products
    }
    return render(request,'core/order-detail.html', context)

@login_required
def wishlist_view(request):
    wishlist = wishlist_model.objects.all()
    context = {
        "wishlists":wishlist
    }
    return render(request,"core/wishlist.html", context)

def add_to_wishlist(request):
    product_id = request.GET['id']
    product = Product.objects.get(id=product_id)
    context = {}
    wishlist_count = wishlist_model.objects.filter(product=product, user=request.user).count()
    
    if wishlist_count > 0:
        context = {
            "bool": True
        }
    else:
        new_wishlist = wishlist_model.objects.create(
            product = product,
            user = request.user
        )
        context = {
            "bool" : True
        }
    

templates/core/category-product-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}   
    <main class="main">
        <div class="page-header mt-30 mb-50">
            <div class="container">
                <div class="archive-header">
                    <div class="row align-items-center">
                        <div class="col-xl-3">
                            <h1 class="mb-15">{{category.title}}</h1>
                            <div class="breadcrumb">
                                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                                <span></span> Shop <span></span> {{category.title}}
                            </div>
                        </div>
                        <!--<div class="col-xl-9 text-end d-none d-xl-block">
                            <ul class="tags-list">
                                <li class="hover-up">
                                    <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Cabbage</a>
                                </li>
                                <li class="hover-up active">
                                    <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Broccoli</a>
                                </li>
                                <li class="hover-up">
                                    <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Artichoke</a>
                                </li>
                                <li class="hover-up">
                                    <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Celery</a>
                                </li>
                                <li class="hover-up mr-0">
                                    <a href="blog-category-grid.html"><i class="fi-rs-cross mr-10"></i>Spinach</a>
                                </li>
                            </ul>
                        </div>-->
                    </div>
                </div>
            </div>
        </div>
        <div class="container mb-30">
            <div class="row">
                <div class="col-12">
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p>We found <strong class="text-brand">{{products.count}}</strong> item{{products.count|pluralize}} for you!</p>
                        </div>
                        <div class="sort-by-product-area">
                            <div class="sort-by-cover mr-10">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps"></i>Show:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">50</a></li>
                                        <li><a href="#">100</a></li>
                                        <li><a href="#">150</a></li>
                                        <li><a href="#">200</a></li>
                                        <li><a href="#">All</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sort-by-cover">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">Featured</a></li>
                                        <li><a href="#">Price: Low to High</a></li>
                                        <li><a href="#">Price: High to Low</a></li>
                                        <li><a href="#">Release Date</a></li>
                                        <li><a href="#">Avg. Rating</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row product-grid">
                        {% for p in products%}
                        <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                            <div class="product-cart-wrap mb-30">
                                <div class="product-img-action-wrap">
                                    <div class="product-img product-img-zoom">
                                        <a href="{% url 'core:product-detail' p.pid %}">
                                            <img class="default-img" src="{{p.image.url}}" alt="" />
                                            <img class="hover-img" src="{{p.image.url}}" alt="" />
                                        </a>
                                    </div>
                                    <div class="product-action-1">
                                        <a aria-label="Add To Wishlist" class="action-btn" href="shop-wishlist.html"><i class="fi-rs-heart"></i></a>
                                        <!--<a aria-label="Compare" class="action-btn" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a>-->
                                        <a aria-label="Quick view" class="action-btn" href="{% url 'core:product-detail' p.pid %}"><i class="fi-rs-eye"></i></a>
                                    </div>
                                    <div class="product-badges product-badges-position product-badges-mrg">
                                        <span class="hot">-{{p.get_precentage|floatformat:0}}%</span>
                                    </div>
                                </div>
                                <div class="product-content-wrap">
                                    <div class="product-category">
                                        <a href="shop-grid-right.html">{{p.category.title}}</a>
                                    </div>
                                    <h2><a href="">{{category.title}}</a></h2>
                                    <!--<div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width: 90%"></div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> (4.0)</span>
                                    </div>-->
                                    <div>
                                        <span class="font-small text-muted">By <a href="vendor-details-1.html">Renisu</a></span>
                                    </div>
                                    <div class="product-card-bottom">
                                        <div class="product-price">
                                            <span>$</span><span class="current-product-price-{{p.id}}">{{p.price}}</span>
                                            <span class="old-price">${{p.old_price}}</span>
                                        </div>
                                        <br>
                                        <div class="add-cart">
                                                <input type="hidden" value="1" class="product-quantity-{{p.id}}">
                                                <input type="hidden" class="product-pid-{{ p.id }}" value="{{ p.pid }}">
                                                <input type="hidden" class="product-image-{{ p.id }}" value="{{ p.image.url }}">
                                                <input type="hidden" class="product-id-{{ p.id }}" value="{{ p.id }}">
                                                <input type="hidden" class="product-title-{{ p.id }}" value="{{ p.title }}">
                                            <!--<a class="add" href="shop-cart.html"><i class="fi-rs-shopping-cart mr-5"></i>Add </a>-->
                                            <div class="d-flex">
                                                <button class="add add-to-cart-btn" data-index="{{ p.id }}" style="border: none 5px;" id="add-to-cart-btn"><i class="fi-rs-shopping-cart mr-5"></i>Add</button>
                                                <button style="border: none; background: none;" class="add-to-wishlist" data-product-item="{{p.id}}"><i class="fi-rs-heart" style="fill: aqua;"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {%endfor%}
                    </div>
                    <!--product grid-->
                    <!--<div class="pagination-area mt-20 mb-20">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-start">
                                <li class="page-item">
                                    <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item active"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                <li class="page-item"><a class="page-link" href="#">6</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                                </li>
                            </ul>
                        </nav>
                    </div>-->
                    <section class="section-padding pb-5">
                        <div class="section-title">
                            <h3 class="">Deals Of The Day</h3>
                            <a class="show-all" href="{% url 'core:wip'%}">
                                All Deals
                                <i class="fi-rs-angle-right"></i>
                            </a>
                        </div>
                        
                        <div class="row">
                            {% for p in products %}
                            <div class="col-xl-3 col-lg-4 col-md-6">
                                
                                <div class="product-cart-wrap style-2">
                                    <div class="product-img-action-wrap">
                                        <div class="product-img"> <!-- Change the image sze here to make it look small -->
                                            <a href="{% url 'core:product-detail' p.pid %}">
                                                <img src="{{p.image.url}}" alt="" style="border:5px solid black"/>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="product-content-wrap">
                                        <div class="deals-countdown-wrap">
                                            <div class="deals-countdown" data-countdown="2025/03/25 00:00:00"></div>
                                        </div>
                                        <div class="deals-content">
                                            <h2><a href="{% url 'core:wip'%}">{{p.title}}</a></h2>
                                            <div>
                                                <span class="font-small text-muted">By <a href="#">Renisu</a></span>
                                            </div>
                                            <div class="product-card-bottom">
                                                <div class="product-price">
                                                    <span>{{p.price}}</span>
                                                    <span class="old-price">{{p.old_price}}</span>
                                                </div>
                                                <div class="add-cart">
                                                    <a class="add" href="{% url 'core:wip'%}"><i class="fi-rs-shopping-cart mr-5"></i>Add </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </section>
                    <!--End Deals-->
                </div>
            </div>
        </div>
    </main>
{%endblock content%}

templates/core/wishlist.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main" id="wishlist-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop <span></span> Fillter
                </div>
            </div>
        </div>
        <div class="container mb-30 mt-50">
            <div class="row">
                <div class="col-xl-10 col-lg-12 m-auto">
                    <div class="mb-50">
                        <h1 class="heading-2 mb-10">Your Wishlist</h1>
                        <h6 class="text-body">There are <span class="text-brand">{{wishlists.count}}</span> products in this list</h6>
                    </div>
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="" />
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col" colspan="2">Product</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Stock Status</th>
                                    <th scope="col">Action</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for w in wishlists%}
                                
                                <tr class="pt-30">
                                    <td class="custome-checkbox pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                        <label class="form-check-label" for="exampleCheckbox1"></label>
                                    </td>
                                    <td class="image product-thumbnail pt-40"><img src="{{w.product.image.url}}" alt="#" /></td>
                                    <td class="product-des product-name">
                                        <h6><a class="product-name mb-10" href="{% url 'core:product-detail' w.product.pid %}">{{ w.product.title|truncatechars:30 }}</a></h6>
                                        
                                    </td>
                                    <td class="price d-fdlex fs-1" data-title="Price">
                                        <span class="text-brand">$</span><span class="text-brand current-product-price-{{ w.product.id }}">{{ w.product.price }}</span>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <span class="stock-status in-stock mb-0"> {% if w.product.in_stock %} In Stock {% else %} Out of Stock {% endif %}</span>
                                    </td>
                                    <td class="text-right" data-title="Cart">


                                        <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ w.product.id }}">
                                        <input type="hidden" class="product-pid-{{ w.product.id }}" value="{{ w.product.pid }}">
                                        <input type="hidden" class="product-image-{{ w.product.id }}" value="{{ w.product.image.url }}">
                                        <input type="hidden" class="product-id-{{ w.product.id }}" value="{{ w.product.id }}">
                                        <input type="hidden" class="product-title-{{ w.product.id }}" value="{{ w.product.title }}">

                                        <button class="btn btn-sm add-to-cart-btn" data-index="{{ w.product.id }}">Add to cart</button>
                                    </td>
                                    <td class="action text-center" data-title="Remove">
                                        <button style="border: none; background: none;" data-wishlist-product="{{ w.id }}"  class="text-body delete-wishlist-product"><i class="fi-rs-trash"></i></button>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td><p>Nothing in wishlist yet...</p></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}
    